/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JgroupBankId {
        /**
          * Endpoint that starts an authentication transaction - required when type is 'auth'.
         */
        "authUrl": string;
        /**
          * Auto-starts the flow immediately on mount, skipping the start button - desktop (qr flow) only.
         */
        "autoStartSingleOption": false;
        /**
          * Endpoint called to cancel an in-progress transaction.
         */
        "cancelUrl": string;
        /**
          * Endpoint polled for the transaction's current status.
         */
        "collectUrl": string;
        /**
          * Renders the widget with its dark color scheme.
         */
        "darkTheme": false;
        /**
          * UI language for all widget copy.
         */
        "language": 'sv' | 'en';
        /**
          * Endpoint that starts a signing transaction - required when type is 'sign'.
         */
        "signUrl": string;
        /**
          * Whether this widget performs an authentication or a signing flow.
         */
        "type": 'auth' | 'sign';
    }
}
export interface JgroupBankIdCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJgroupBankIdElement;
}
declare global {
    interface HTMLJgroupBankIdElementEventMap {
        "cancelled": any;
        "completed": any;
        "started": any;
    }
    interface HTMLJgroupBankIdElement extends Components.JgroupBankId, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJgroupBankIdElementEventMap>(type: K, listener: (this: HTMLJgroupBankIdElement, ev: JgroupBankIdCustomEvent<HTMLJgroupBankIdElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJgroupBankIdElementEventMap>(type: K, listener: (this: HTMLJgroupBankIdElement, ev: JgroupBankIdCustomEvent<HTMLJgroupBankIdElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJgroupBankIdElement: {
        prototype: HTMLJgroupBankIdElement;
        new (): HTMLJgroupBankIdElement;
    };
    interface HTMLElementTagNameMap {
        "jgroup-bank-id": HTMLJgroupBankIdElement;
    }
}
declare namespace LocalJSX {
    interface JgroupBankId {
        /**
          * Endpoint that starts an authentication transaction - required when type is 'auth'.
         */
        "authUrl": string;
        /**
          * Auto-starts the flow immediately on mount, skipping the start button - desktop (qr flow) only.
         */
        "autoStartSingleOption"?: false;
        /**
          * Endpoint called to cancel an in-progress transaction.
         */
        "cancelUrl": string;
        /**
          * Endpoint polled for the transaction's current status.
         */
        "collectUrl": string;
        /**
          * Renders the widget with its dark color scheme.
         */
        "darkTheme"?: false;
        /**
          * UI language for all widget copy.
         */
        "language"?: 'sv' | 'en';
        /**
          * Fired when the visitor cancels the flow, either via the cancel button or a call to cancel().
         */
        "onCancelled"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Fired once collect() resolves with a terminal 'complete' status - detail carries the raw collect response, success or business-logic error.
         */
        "onCompleted"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Fired once the initial auth/sign request has succeeded and a transaction is under way - detail carries { flowType }, so consumers can tell the same-device app hand-off (flowType: 'app', which then shows nothing of its own until the visitor returns) apart from the qr flow's own continuously-updating UI.
         */
        "onStarted"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Endpoint that starts a signing transaction - required when type is 'sign'.
         */
        "signUrl": string;
        /**
          * Whether this widget performs an authentication or a signing flow.
         */
        "type": 'auth' | 'sign';
    }
    interface IntrinsicElements {
        "jgroup-bank-id": JgroupBankId;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jgroup-bank-id": LocalJSX.JgroupBankId & JSXBase.HTMLAttributes<HTMLJgroupBankIdElement>;
        }
    }
}
