/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JgroupBankId {
        /**
          * Endpoint that starts an authentication transaction - required when type is 'auth'.
         */
        "authUrl": string;
        /**
          * Auto-starts the flow immediately on mount, skipping the start button - desktop (qr flow) only.
         */
        "autoStartSingleOption": false;
        /**
          * Endpoint called to cancel an in-progress transaction.
         */
        "cancelUrl": string;
        /**
          * Endpoint polled for the transaction's current status.
         */
        "collectUrl": string;
        /**
          * Renders the widget with its dark color scheme.
         */
        "darkTheme": false;
        /**
          * UI language for all widget copy.
         */
        "language": 'sv' | 'en';
        /**
          * Corner style for the start button and its BankID badge: 'full' (the default) is a pill/circle, 'md' is still visibly rounded (rounded-xl/rounded-lg) but not a full pill/circle.
         */
        "rounded": 'full' | 'md';
        /**
          * Endpoint that starts a signing transaction - required when type is 'sign'.
         */
        "signUrl": string;
        /**
          * Whether this widget performs an authentication or a signing flow.
         */
        "type": 'auth' | 'sign';
    }
    /**
     * Just the BankID button's own look - the avatar badge, the label, the
     * loading spinner - with none of the actual auth/collect/cancel flow
     * logic <jgroup-bank-id> has. For a consumer that already drives its own
     * identification flow some other way (e.g. opening a popup window running
     * the real <jgroup-bank-id> widget on a separate page, then reacting to a
     * postMessage/postRobot event once it completes) and just wants this
     * widget's own button to trigger that, instead of maintaining a separate,
     * hand-rolled replica of it.
     * Shares StartButton (and its BankIdLogo/Spinner) directly from
     * jgroup-bank-id's own components.tsx - one visual definition, not a
     * second copy that can drift from the real widget's own button over time.
     */
    interface JgroupBankIdButton {
        /**
          * Renders with the dark color scheme.
         */
        "darkTheme": false;
        /**
          * Button label.
         */
        "label": string;
        /**
          * Swaps the label out for a spinner and disables the button - the only disabled state StartButton itself actually supports (no separate "disabled but still showing the label" state to extract).
         */
        "loading": false;
        /**
          * Corner style for the button and its BankID badge: 'full' (the default) is a pill/circle, 'md' is still visibly rounded (rounded-xl/rounded-lg) but not a full pill/circle.
         */
        "rounded": 'full' | 'md';
    }
}
export interface JgroupBankIdCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJgroupBankIdElement;
}
declare global {
    interface HTMLJgroupBankIdElementEventMap {
        "cancelled": any;
        "completed": any;
        "started": any;
    }
    interface HTMLJgroupBankIdElement extends Components.JgroupBankId, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJgroupBankIdElementEventMap>(type: K, listener: (this: HTMLJgroupBankIdElement, ev: JgroupBankIdCustomEvent<HTMLJgroupBankIdElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJgroupBankIdElementEventMap>(type: K, listener: (this: HTMLJgroupBankIdElement, ev: JgroupBankIdCustomEvent<HTMLJgroupBankIdElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJgroupBankIdElement: {
        prototype: HTMLJgroupBankIdElement;
        new (): HTMLJgroupBankIdElement;
    };
    /**
     * Just the BankID button's own look - the avatar badge, the label, the
     * loading spinner - with none of the actual auth/collect/cancel flow
     * logic <jgroup-bank-id> has. For a consumer that already drives its own
     * identification flow some other way (e.g. opening a popup window running
     * the real <jgroup-bank-id> widget on a separate page, then reacting to a
     * postMessage/postRobot event once it completes) and just wants this
     * widget's own button to trigger that, instead of maintaining a separate,
     * hand-rolled replica of it.
     * Shares StartButton (and its BankIdLogo/Spinner) directly from
     * jgroup-bank-id's own components.tsx - one visual definition, not a
     * second copy that can drift from the real widget's own button over time.
     */
    interface HTMLJgroupBankIdButtonElement extends Components.JgroupBankIdButton, HTMLStencilElement {
    }
    var HTMLJgroupBankIdButtonElement: {
        prototype: HTMLJgroupBankIdButtonElement;
        new (): HTMLJgroupBankIdButtonElement;
    };
    interface HTMLElementTagNameMap {
        "jgroup-bank-id": HTMLJgroupBankIdElement;
        "jgroup-bank-id-button": HTMLJgroupBankIdButtonElement;
    }
}
declare namespace LocalJSX {
    interface JgroupBankId {
        /**
          * Endpoint that starts an authentication transaction - required when type is 'auth'.
         */
        "authUrl": string;
        /**
          * Auto-starts the flow immediately on mount, skipping the start button - desktop (qr flow) only.
         */
        "autoStartSingleOption"?: false;
        /**
          * Endpoint called to cancel an in-progress transaction.
         */
        "cancelUrl": string;
        /**
          * Endpoint polled for the transaction's current status.
         */
        "collectUrl": string;
        /**
          * Renders the widget with its dark color scheme.
         */
        "darkTheme"?: false;
        /**
          * UI language for all widget copy.
         */
        "language"?: 'sv' | 'en';
        /**
          * Fired whenever the widget returns to its idle state - the cancel button, "try again" after a failure, or an unexpected drop mid-flow. Use it to reset any "a BankID attempt is in progress" state a consuming app keeps of its own.
         */
        "onCancelled"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Fired once collect() resolves with a terminal 'complete' status - detail carries the raw collect response, success or business-logic error.
         */
        "onCompleted"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Fired once the initial auth/sign request has succeeded and a transaction is under way - detail carries { flowType }, so consumers can tell the same-device app hand-off (flowType: 'app', which then shows nothing of its own until the visitor returns) apart from the qr flow's own continuously-updating UI.
         */
        "onStarted"?: (event: JgroupBankIdCustomEvent<any>) => void;
        /**
          * Corner style for the start button and its BankID badge: 'full' (the default) is a pill/circle, 'md' is still visibly rounded (rounded-xl/rounded-lg) but not a full pill/circle.
         */
        "rounded"?: 'full' | 'md';
        /**
          * Endpoint that starts a signing transaction - required when type is 'sign'.
         */
        "signUrl": string;
        /**
          * Whether this widget performs an authentication or a signing flow.
         */
        "type": 'auth' | 'sign';
    }
    /**
     * Just the BankID button's own look - the avatar badge, the label, the
     * loading spinner - with none of the actual auth/collect/cancel flow
     * logic <jgroup-bank-id> has. For a consumer that already drives its own
     * identification flow some other way (e.g. opening a popup window running
     * the real <jgroup-bank-id> widget on a separate page, then reacting to a
     * postMessage/postRobot event once it completes) and just wants this
     * widget's own button to trigger that, instead of maintaining a separate,
     * hand-rolled replica of it.
     * Shares StartButton (and its BankIdLogo/Spinner) directly from
     * jgroup-bank-id's own components.tsx - one visual definition, not a
     * second copy that can drift from the real widget's own button over time.
     */
    interface JgroupBankIdButton {
        /**
          * Renders with the dark color scheme.
         */
        "darkTheme"?: false;
        /**
          * Button label.
         */
        "label": string;
        /**
          * Swaps the label out for a spinner and disables the button - the only disabled state StartButton itself actually supports (no separate "disabled but still showing the label" state to extract).
         */
        "loading"?: false;
        /**
          * Corner style for the button and its BankID badge: 'full' (the default) is a pill/circle, 'md' is still visibly rounded (rounded-xl/rounded-lg) but not a full pill/circle.
         */
        "rounded"?: 'full' | 'md';
    }
    interface IntrinsicElements {
        "jgroup-bank-id": JgroupBankId;
        "jgroup-bank-id-button": JgroupBankIdButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jgroup-bank-id": LocalJSX.JgroupBankId & JSXBase.HTMLAttributes<HTMLJgroupBankIdElement>;
            /**
             * Just the BankID button's own look - the avatar badge, the label, the
             * loading spinner - with none of the actual auth/collect/cancel flow
             * logic <jgroup-bank-id> has. For a consumer that already drives its own
             * identification flow some other way (e.g. opening a popup window running
             * the real <jgroup-bank-id> widget on a separate page, then reacting to a
             * postMessage/postRobot event once it completes) and just wants this
             * widget's own button to trigger that, instead of maintaining a separate,
             * hand-rolled replica of it.
             * Shares StartButton (and its BankIdLogo/Spinner) directly from
             * jgroup-bank-id's own components.tsx - one visual definition, not a
             * second copy that can drift from the real widget's own button over time.
             */
            "jgroup-bank-id-button": LocalJSX.JgroupBankIdButton & JSXBase.HTMLAttributes<HTMLJgroupBankIdButtonElement>;
        }
    }
}
